version: "3"
services:
  mysql56:
    image: "mysql:5.6"
    container_name: "mysql56"
    ports:
    - "13306:3306"
    environment:
#      这个是必填的项目
      MYSQL_ROOT_PASSWORD: "Syq"
#      这个是选填的项目，如果填上，容器在启动的时候将会创建该数据库
      MYSQL_DATABASE: "db_tiny_url"
#      更改时区
      TZ: "Asia/shanghai"
#      创建数据卷，用于保存容器写的数据
    volumes:
    - /home/lomogo/docker/mysql:/var/lib/mysql
#    同步Mysql时区
    command: "--default-time_zone='+8:00'"
  tinyurl:
#    根据当前目录的Dockerfile文件生成镜像
    build: .
#    创建tinyurl的归档日志数据卷
    volumes:
      - /home/lomogo/docker/project/tinyurl/log:/log
      - /home/lomogo/docker/project/tinyurl/data/images/qrcode:/data/images/qrcode
    container_name: "tinyurl"
#    depends_on会定义启动顺序，但是并不是说第一个容器完全启动之后才再启动下一个容器。因此下面需要利用wait-for.sh脚本来确保mysql服务启动之后再启动应用。
    depends_on:
      - mysql56
    ports:
    - "8080:8080"
    command: bash -c "./wait-for.sh mysql56:3306 -- ./tinyURL"