[app]
url = "127.0.0.1"
port = ":8080"

[mysql]
user = "root"
password = "Syq"
host = "mysql55"
port = 3306
dbname = "db_short_link"
maxopenconn = 40
maxidleconn = 25

[zap]
filename = "log/tinyURL.log"
maxsize = 10
maxbackups = 5
maxage = 30
compress = false
level = "debug"
