[app]
host = "127.0.0.1"
port = 8080

[mysql]
user = "root"
password = "Syq"
#如果要在docker下运行，注释这一条语句
host = "127.0.0.1"
#如果不依赖docker运行，注释这条语句
#host = "mysql56"
port = 3306
dbname = "db_tiny_url"
maxopenconn = 40
maxidleconn = 25

[zap]
filename = "log/tinyURL.log"
maxsize = 10
maxbackups = 5
maxage = 30
compress = false
level = "debug"

[qrcode]
imgheight = 256
filepath = "data/images/qrcode/"

[email]
timeout = 10
connnum = 40
from = "dhdpat@163.com"
port = 25
host = "smtp.163.com"
secret = "BNYNKQWZHZTHNIJS"
