// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "lomogo"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/email": {
            "post": {
                "description": "将生成的二维码和短链接发送到用户邮箱，链接必须以：http://或https://开头。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "邮件"
                ],
                "summary": "发送邮件",
                "parameters": [
                    {
                        "description": "需要转换的网址",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.EmailInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": \"0\", \"msg\": \"成功\", \"details\": \"\", data:\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/link": {
            "post": {
                "description": "将用户传入的网址转换为短链接, 链接必须以：http://或https://开头",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链"
                ],
                "summary": "生成短链",
                "parameters": [
                    {
                        "description": "需要转换的网址",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.URLInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": \"0\", \"msg\": \"成功\", \"details\": \"\", data:\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/qrcode": {
            "post": {
                "description": "将用户传入的网址转换为二维码，链接必须以：http://或https://开头",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "二维码"
                ],
                "summary": "生成二维码",
                "parameters": [
                    {
                        "description": "需要转换的网址",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.URLInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": \"0\", \"msg\": \"成功\", \"details\": \"\", data:\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.EmailInfo": {
            "type": "object",
            "properties": {
                "recipient": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "request.URLInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "127.0.0.1:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "短链接服务接口文档",
	Description: "该服务用以生成短链接",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
