basePath: /api/v1
definitions:
  request.EmailInfo:
    properties:
      recipient:
        type: string
      url:
        type: string
    type: object
  request.URLInfo:
    properties:
      url:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    name: lomogo
  description: 该服务用以生成短链接
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 短链接服务接口文档
  version: 0.0.1
paths:
  /email:
    post:
      consumes:
      - application/json
      description: 将生成的二维码和短链接发送到用户邮箱，链接必须以：http://或https://开头。
      parameters:
      - description: 需要转换的网址
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.EmailInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "0", "msg": "成功", "details": "", data:""}'
          schema:
            type: string
      summary: 发送邮件
      tags:
      - 邮件
  /link:
    post:
      consumes:
      - application/json
      description: 将用户传入的网址转换为短链接, 链接必须以：http://或https://开头
      parameters:
      - description: 需要转换的网址
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.URLInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "0", "msg": "成功", "details": "", data:""}'
          schema:
            type: string
      summary: 生成短链
      tags:
      - 短链
  /qrcode:
    post:
      consumes:
      - application/json
      description: 将用户传入的网址转换为二维码，链接必须以：http://或https://开头
      parameters:
      - description: 需要转换的网址
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.URLInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "0", "msg": "成功", "details": "", data:""}'
          schema:
            type: string
      summary: 生成二维码
      tags:
      - 二维码
swagger: "2.0"
